name: "Colorfully, Tyler"
description: "my own piece of the internets"

url: "www.colorfullytyler.com"

paginate: 10

markdown: kramdown
permalink: pretty
highlighter: pygments

excerpt_separator: <!--more-->
theme: jekyll-theme-midnight